import "@/app/globals.css";
import { ToastProvider } from "@/components/provider";
import { Toast } from "@/components/reusable";
import { useCurrentUser } from "@/hooks";
import { redirect } from "next/navigation";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const current = await useCurrentUser()

  if (current) {
      redirect("/");
    }
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <main className="relative bg-gray-400 h-screen grid items-center">
            {children}
          </main>
        </ToastProvider>
      </body>
    </html>
  )
}
